site_name: kelp-wanted-competition
site_description: Estimating the extent of Giant Kelp Forests by segmenting Landsat imagery
site_dir: docs-site
repo_url: https://github.com/xultaeculcis/kelp-wanted-competition
edit_uri: edit/main/docs
copyright: Copyright 2023 xultaeculcis
theme:
  name: material
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - md_in_html
  - meta
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.tabbed
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_toc_entry: False
            show_root_full_path: True
            show_root_members_full_path: True
            show_object_full_path: True
            show_root_heading: False
            show_source: True
            show_category_heading: False
            show_bases: True
            show_signature: False
            filters:
              - "!^_"  # exclude all members starting with _
            heading_level: 3
watch:
  - kelp/
nav:
  - Home: index.md
  - Guides:
      - Setting up dev environment: "guides/setup-dev-env.md"
      - Contributing: "guides/contributing.md"
      - Running tests: "guides/tests.md"
      - Using Makefile commands: "guides/makefile-usage.md"
  - API reference:
      - kelp.consts: "api_ref/kelp.consts.md"
      - kelp.core: "api_ref/kelp.core.md"
      - kelp.utils: "api_ref/kelp.utils.md"
