steps:
  - task: AzureCLI@2
    displayName: Connect to AML Workspace using CLI v2
    inputs:
      azureSubscription: $(ADO__SERVICE_CONNECTION_AML_WS)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az configure --defaults group=$(AML__RESOURCE_GROUP) workspace=$(AML__WORKSPACE_NAME)
