steps:
  - task: AzureCLI@2
    displayName: Install AML CLI v2
    inputs:
      azureSubscription: $(ADO__SERVICE_CONNECTION_AML_WS)
      scriptType: bash
      scriptLocation: inlineScript
      workingDirectory: code/
      inlineScript: |
        set -e # fail on error
        az version
        az extension add -n ml -y
        az extension update -n ml
        az extension list
