$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train
version: 0.0.1
display_name: Model training
description: Trains the Kelp Forest Segmentation model.

inputs:
  data_dir:
    type: uri_folder
    description: The training data dir.
  metadata_file:
    type: uri_file
    description: The metadata file.
  has_kelp_importance_factor:
    type: number
    default: 1.0
    description: The importance factor for has_kelp flag.
  kelp_pixels_pct_importance_factor:
    type: number
    default: 1.0
    description: The importance factor for kelp pixels percentage.
  qa_ok_importance_factor:
    type: number
    default: 1.0
    description: The importance factor for qa_ok flag.
  qa_corrupted_pixels_pct_importance_factor:
    type: number
    default: 1.0
    description: The importance factor for QA layer corrupted pixels percentage.
  almost_all_water_importance_factor:
    type: number
    default: 1.0
    description: The importance factor for almost_all_water flag.
  dem_nan_pixels_pct_importance_factor:
    type: number
    default: 1.0
    description: The importance factor for DEM layer zero pixels percentage.
  dem_zero_pixels_pct_importance_factor:
    type: number
    default: 1.0
    description: The importance factor for DEM layer NaN pixels percentage.

outputs:
  output_dir:
    type: uri_folder
    description: The output dir.

environment: azureml:acpt-train-env@latest

resources:
  shm_size: "8g"

code: ../..
command: >-
  PYTHONPATH=$PYTHONPATH:. ; export PYTHONPATH ;
  python ./kelp/entrypoints/train.py
  --data_dir ${{inputs.data_dir}}
  --output_dir ${{outputs.output_dir}}
  --metadata_fp ${{inputs.metadata_file}}
  --cv_split 6
  --batch_size 32
  --num_workers 4
  --band_order 2,3,4,0,1,5,6
  --image_size 352
  --use_weighted_sampler
  --samples_per_epoch 5120
  --has_kelp_importance_factor ${{inputs.has_kelp_importance_factor}}
  --kelp_pixels_pct_importance_factor ${{inputs.kelp_pixels_pct_importance_factor}}
  --qa_ok_importance_factor ${{inputs.qa_ok_importance_factor}}
  --qa_corrupted_pixels_pct_importance_factor ${{inputs.qa_corrupted_pixels_pct_importance_factor}}
  --almost_all_water_importance_factor ${{inputs.almost_all_water_importance_factor}}
  --dem_nan_pixels_pct_importance_factor ${{inputs.dem_nan_pixels_pct_importance_factor}}
  --dem_zero_pixels_pct_importance_factor ${{inputs.dem_zero_pixels_pct_importance_factor}}
  --normalization_strategy quantile
  --architecture unet
  --encoder resnet50
  --pretrained
  --encoder_weights imagenet
  --lr 3e-4
  --optimizer adamw
  --weight_decay 1e-4
  --lr_scheduler onecycle
  --pct_start 0.3
  --div_factor 2
  --final_div_factor 1e2
  --loss dice
  --strategy no-freeze
  --monitor_metric val/dice
  --save_top_k 1
  --early_stopping_patience 7
  --precision 16-mixed
  --epochs 10
is_deterministic: false
