$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train
version: 0.0.1
display_name: Model training
description: Trains the Kelp Forest Segmentation model.

inputs:
  data_dir:
    type: uri_folder
    description: The training data dir.
  metadata_file:
    type: uri_file
    description: The metadata file.
  dataset_stats_file:
    type: uri_file
    description: The dataset stats file.
  cv_split:
    type: integer
    default: 0
    description: The CV split number.

outputs:
  output_dir:
    type: uri_folder
    description: The output dir.

environment: azureml:acpt-train-env@latest

resources:
  shm_size: "14g"

code: ../..
command: >-
  PYTHONPATH=$PYTHONPATH:. ; export PYTHONPATH ;
  python ./kelp/nn/training/train.py
  --data_dir ${{inputs.data_dir}}
  --output_dir ${{outputs.output_dir}}
  --metadata_fp ${{inputs.metadata_file}}
  --dataset_stats_fp ${{inputs.dataset_stats_file}}
  --cv_split ${{inputs.cv_split}}
  --batch_size 32
  --num_workers 4
  --bands SWIR,NIR,R,G,B,QA,DEM
  --spectral_indices DEMWM,NDVI,ATSAVI,AVI,CI,ClGreen,GBNDVI,GVMI,IPVI,KIVU,MCARI,MVI,NormNIR,PNDVI,SABI,WDRVI,mCRIG
  --resize_strategy pad
  --image_size 352
  --fill_missing_pixels_with_torch_nan
  --mask_using_qa
  --mask_using_water_mask
  --use_weighted_sampler
  --samples_per_epoch 10240
  --has_kelp_importance_factor 3
  --kelp_pixels_pct_importance_factor 0.2
  --qa_ok_importance_factor 0
  --qa_corrupted_pixels_pct_importance_factor -1
  --almost_all_water_importance_factor 0.5
  --dem_nan_pixels_pct_importance_factor 0.25
  --dem_zero_pixels_pct_importance_factor -1
  --normalization_strategy quantile
  --architecture unet
  --encoder tu-efficientnet_b5
  --pretrained
  --encoder_weights imagenet
  --lr 3e-4
  --optimizer adamw
  --weight_decay 1e-4
  --lr_scheduler onecycle
  --loss dice
  --tta
  --tta_merge_mode max
  --monitor_metric val/dice
  --save_top_k 1
  --early_stopping_patience 50
  --precision 16-mixed
  --epochs 10

is_deterministic: false
