$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train
version: 0.0.1
display_name: Model training
description: Trains the Kelp Forest Segmentation model.

inputs:
  data_dir:
    type: uri_folder
    description: The training data dir.
  metadata_file:
    type: uri_file
    description: The metadata file.
  dataset_stats_file:
    type: uri_file
    description: The dataset stats file.
  spectral_indices:
    type: string
    default: CDOM,DOC,WATERCOLOR,SABI,KIVU,Kab1,NDAVI,WAVI
    description: The spectral indices.

outputs:
  output_dir:
    type: uri_folder
    description: The output dir.

environment: azureml:acpt-train-env@latest

resources:
  shm_size: "12g"

code: ../..
command: >-
  PYTHONPATH=$PYTHONPATH:. ; export PYTHONPATH ;
  python ./kelp/entrypoints/train.py
  --data_dir ${{inputs.data_dir}}
  --output_dir ${{outputs.output_dir}}
  --metadata_fp ${{inputs.metadata_file}}
  --dataset_stats_fp ${{inputs.dataset_stats_file}}
  --spectral_indices ${{inputs.spectral_indices}}
  --cv_split 6
  --batch_size 32
  --num_workers 4
  --band_order 2,3,4,0,1,5,6
  --image_size 352
  --fill_missing_pixels_with_torch_nan
  --mask_using_qa
  --mask_using_water_mask
  --use_weighted_sampler
  --samples_per_epoch 5120
  --has_kelp_importance_factor 3
  --kelp_pixels_pct_importance_factor 0.2
  --qa_ok_importance_factor 0
  --qa_corrupted_pixels_pct_importance_factor -1
  --almost_all_water_importance_factor 0.5
  --dem_nan_pixels_pct_importance_factor 0.25
  --dem_zero_pixels_pct_importance_factor -1
  --normalization_strategy quantile
  --architecture unet
  --encoder resnet50
  --pretrained
  --encoder_weights imagenet
  --lr 3e-4
  --optimizer adamw
  --weight_decay 1e-4
  --lr_scheduler onecycle
  --pct_start 0.3
  --div_factor 2
  --final_div_factor 1e2
  --loss dice
  --strategy no-freeze
  --monitor_metric val/dice
  --save_top_k 1
  --early_stopping_patience 7
  --precision 16-mixed
  --epochs 10
is_deterministic: false
