$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Hyperparameter search with CV splits
experiment_name: cv-split-hparam-search

settings:
  default_compute: azureml:gpu-4c-28g-t4-nc4ast4v3-spot
  default_datastore: azureml:workspaceblobstore

jobs:
  sweep_step:
    type: sweep

    resources:
      shm_size: "12g"

    inputs:
      data_dir:
        type: uri_folder
        mode: download
        path: azureml:train_dataset@latest
      metadata_file:
        type: uri_file
        mode: download
        path: azureml:metadata_file@latest
      dataset_stats_file:
        type: uri_file
        mode: download
        path: azureml:dataset_stats_file:2

    outputs:
      output_dir:

    sampling_algorithm: random

    trial: file:../components/train_split.yaml

    search_space:
      cv_split:
        type: choice
        values:
          - 3
          - 4
          - 6
          - 8
      encoder:
        type: choice
        values:
          - tu-mobilevitv2_150.cvnets_in22k_ft_in1k_384
          - tu-maxvit_small_tf_384.in1k
          - tu-seresnextaa101d_32x8d.sw_in12k_ft_in1k
          - tu-rexnetr_200.sw_in12k_ft_in1k
          - tu-seresnext26d_32x4d
          - tu-gcresnet33ts.ra2_in1k
          - tu-seresnext101_32x4d
      architecture:
        type: choice
        values:
          - linknet
          - unet
          - unet++

    objective:
      goal: maximize
      primary_metric: hp_metric

    limits:
      max_total_trials: 10
      max_concurrent_trials: 50
      trial_timeout: 3600  # 1 hour
      timeout: 259200  # 3 days
