$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Hyperparameter search for model encoder and architecture
experiment_name: model-hparam-search

settings:
  default_compute: azureml:gpu-4c-28g-t4-nc4ast4v3-spot
  default_datastore: azureml:workspaceblobstore

jobs:
  sweep_step:
    type: sweep

    resources:
      shm_size: "12g"

    inputs:
      data_dir:
        type: uri_folder
        mode: download
        path: azureml:train_dataset@latest
      metadata_file:
        type: uri_file
        mode: download
        path: azureml:metadata_file@latest
      dataset_stats_file:
        type: uri_file
        mode: download
        path: azureml:dataset_stats_file:2

    outputs:
      output_dir:

    sampling_algorithm: random

    trial: file:../components/train_model.yaml

    search_space:
      decoder_channels:
        type: choice
        values:
          - 256,128,64,32,16
          - 256,128,64,32
          - 256,128,64
          - 512,256,128,64,32
          - 512,256,128,64
          - 1024,512,256,128,64
          - 1024,512,256,128
          - 1024,512,256,128,128
          - 1024,512,256,128

    objective:
      goal: maximize
      primary_metric: hp_metric

    limits:
      max_total_trials: 1000
      max_concurrent_trials: 50
      trial_timeout: 3600  # 1 hour
      timeout: 259200  # 3 days
