$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
description: Hyperparameter search for sampler weights
experiment_name: sampler-weights-hparam-search

settings:
  default_compute: azureml:gpu-4c-28g-t4-nc4ast4v3-spot
  default_datastore: azureml:workspaceblobstore

jobs:
  sweep_step:
    type: sweep

    resources:
      shm_size: "12g"

    inputs:
      data_dir:
        type: uri_folder
        mode: download
        path: azureml:train_dataset@latest
      metadata_file:
        type: uri_file
        mode: download
        path: azureml:metadata_file@latest

    outputs:
      output_dir:

    sampling_algorithm: random

    trial: file:../components/train_sampler_weights.yaml

    search_space:
      has_kelp_importance_factor:
        type: choice
        values: [ 0.0, 0.2, 0.5, 1.0, 2.0, 3.0 ]
      kelp_pixels_pct_importance_factor:
        type: choice
        values: [ 0.0, 0.2, 0.5, 1.0, 2.0, 3.0 ]
      qa_ok_importance_factor:
        type: choice
        values: [ -1.0, -0.5, -0.25, 0.0, 0.25, 0.5, 0.75, 1.0 ]
      qa_corrupted_pixels_pct_importance_factor:
        type: choice
        values: [ -1.0, -0.5, -0.25, 0.0, 0.25, 0.5, 0.75, 1.0 ]
      almost_all_water_importance_factor:
        type: choice
        values: [ -1.0, -0.5, -0.25, 0.0, 0.25, 0.5, 0.75, 1.0 ]
      dem_nan_pixels_pct_importance_factor:
        type: choice
        values: [ -1.0, -0.5, -0.25, 0.0, 0.25, 0.5, 0.75, 1.0 ]
      dem_zero_pixels_pct_importance_factor:
        type: choice
        values: [ -1.0, -0.5, -0.25, 0.0, 0.25, 0.5, 0.75, 1.0]

    objective:
      goal: maximize
      primary_metric: hp_metric

    limits:
      max_total_trials: 1000
      max_concurrent_trials: 100
      trial_timeout: 3600  # 1 hour
      timeout: 259200  # 3 days
